//
//  Quotes.swift
//  Wingman
//
//  Source of truth for the Home-screen daily quote pool. Mirrors the contents
//  of `Quotes.txt` — kept here as a Swift literal because the .txt file is not
//  registered as a bundled resource in the Xcode project, and embedding avoids
//  the failure mode where `Bundle.main.url(forResource:)` returns nil.
//

import Foundation

enum Quotes {
    static let all: [String] = [
        "You cannot change what you refuse to confront.",
        "If you don\u{2019}t risk anything, you risk everything.",
        "It\u{2019}s better to know and be disappointed than to never know and always wonder.",
        "The man who moves a mountain begins by carrying away small stones.",
        "Confidence isn\u{2019}t something you\u{2019}re born with. It\u{2019}s something you build",
        "If you don\u{2019}t swing you\u{2019}ll never hit a home run.",
        "Never fear rejection, fear a life of regretting.",
        "Believe you can and you're halfway there.",
        "Energy and persistence conquer all things.",
        "Failure and rejection are the first steps to succeeding.",
        "You miss 100% of the shots you don\u{2019}t take",
        "Rejection is not the end. Just a step on the right path.",
        "Every successful person has faced rejection. The difference is they didn't let it stop them from trying again.",
        "He who is not courageous enough to take risks will accomplish nothing in life.",
        "There will be times when you succeed and there will be times when you fail, and both are equally important.",
        "The biggest risk is not taking any risk.",
        "A person who never made a mistake never tried anything new.",
        "No one can make you feel inferior without your consent.",
        "Don't wait for the opportunities to come. Get up and create them.",
        "Don't worry about failure; you only have to succeed once.",
        "We don't grow when things are easy. We grow when we face challenges.",
        "It's not because things are difficult that we dare not venture. It's because we dare not venture that they are difficult.",
        "If you are not willing to risk the unusual, you will have to settle for the ordinary.",
        "Trust yourself. You are capable of much more than you think.",
        "Whether you think you can or think you can't, you are right.",
        "If you don't try, you'll never know what could of been.",
        "When it feels scary to jump, that is exactly when you jump.",
        "Brave men may not live forever, but cautious men do not live at all.",
        "You can\u{2019}t control peoples actions, but you can control your reaction to them.",
        "Courage is the birthplace of confidence.",
        "It is necessary to put yourself out for rejection and accept that you will be rejected.",
        "You can be the ripest, juiciest peach in the world, and there's still going to be somebody who hates peaches.",
        "One can choose to go back toward safety or forward toward growth.",
        "Change equals self-improvement. Push yourself to places you haven\u{2019}t been before.",
        "Success is the sum of small efforts repeated day in and day out.",
        "Fall seven times and stand up eight.",
        "Happiness depends upon ourselves.",
        "Every \"no\" gets you one step closer to \"yes.\"",
        "Swing the bat \u{2014} home runs don't happen from the bench.",
        "Leap before you're ready; growth happens in mid-air.",
        "The only failure is the one where you stop trying.",
        "Every approach is practice for the one that works.",
        "One bold move beats a lifetime of \"what ifs.\"",
        "The game doesn't start until you step on the field.",
        "Every master was once a beginner who refused to quit.",
        "The only bad approach is the one you didn't make.",
        "No approach is wasted; it either works or reveals what to change.",
        "What you\u{2019}re not changing, you\u{2019}re choosing.",
        "Inaction guarantees nothing happens. Action is the only path that creates possibility.",
        "You don\u{2019}t lose by trying. You lose by never finding out.",
        "Anything that happens beats nothing happening at all.",
        "A man who fears pain more than failure will taste both",
        "The guy who is awkward still beats the guy who never acts.",
        "The door stays closed until you turn the handle. She can\u{2019}t say yes to the version of you that never shows up.",
        "The man you want to be is built one decision at a time.",
        "Comfort zones are quiet places where nothing changes.",
        "If you wait to feel ready, you will wait forever.",
        "You cannot win a game you never play.",
        "Fear loses power when you step toward it.",
        "Change is hard at first, messy in the middle, and gorgeous at the end.",
        "If nothing ever changed, there\u{2019}d be no butterflies.",
        "The greatest glory in living lies not in never falling, but in rising every time we fall.",
        "The most certain way to succeed is always to try just one more time.",
        "Success is not final, failure is not fatal: It is the courage to continue that counts.",
        "The cave you fear to enter holds the treasure you seek.",
        "The only place where success comes before work is in the dictionary.",
        "The only impossible journey is the one you never begin.",
        "Doubt kills more dreams than failure ever will.",
        "If you face towards the sunshine, you\u{2019}ll notice the shadows will fall behind you.",
        "Believe that what you do makes a difference because it does.",
        "The secret of getting ahead is getting started.",
        "Small deeds done are better than great deeds planned.",
        "Do not let what you cannot do interfere with what you can do.",
        "Whatever the mind of man can conceive and believe, it can achieve.",
        "Patience, persistence and perspiration make an unbeatable combination for success.",
        "You don\u{2019}t have to be great to start, but you have to start to be great.",
        "Do today what others won't and achieve tomorrow what others can't.",
        "Don't let the fear of losing be greater than the excitement of winning.",
        "You don\u{2019}t have to see the whole staircase, just take the first step.",
        "The master has failed more times than the beginner has even tried.",
        "Replace fear of the unknown with curiosity.",
        "A ship in the harbour is safe, but that\u{2019}s not what it was made for.",
        "You can choose courage, or you can choose comfort, but you cannot choose both.",
        "Above all, be the heroine of your life, not the victim.",
        "Courage is being scared to death, but moving forward anyway.",
        "Life is not about living the safer option. Life is about living a life worth living.",
        "You cannot swim for new horizons until you have the courage to lose sight of the shore.",
        "You can, you should, and if you\u{2019}re brave enough to start, you will.",
        "It always seems impossible until it\u{2019}s done.",
        "It does not matter how slowly you go as long as you do not stop.",
        "If there is no struggle, there is no progress.",
        "Be not afraid of growing slowly; be afraid only of standing still.",
        "Recognizing that you are not where you want to be is a starting point to begin changing your life.",
        "You can waste your lives drawing lines. Or you can live your life crossing them.",
        "Accept responsibility for your life. Know that it is you who will get you where you want to go, no one else.",
        "Life shrinks or expands in proportion to one's courage.",
        "There is only one way to avoid criticism: do nothing, say nothing, and be nothing.",
        "Everything you\u{2019}ve ever wanted is on the other side of fear.",
        "You can\u{2019}t fall if you don\u{2019}t climb. But there\u{2019}s no joy in living your whole life on the ground.",
        "In order to succeed, your desire for success should be greater than your fear of failure.",
        "All our dreams can come true, if we have the courage to pursue them.",
        "You will never plough a field if you only turn it over in your mind.",
        "Don't wait. The time will never be just right.",
        "Failure is success in progress.",
        "Success is walking from failure to failure with no loss of enthusiasm.",
        "Successful people willingly do what unsuccessful people are unwilling to do.",
        "The only limit to our realization of tomorrow will be our doubts of today.",
        "Happiness is not something ready made. It comes from your own actions.",
        "The successful warrior is the average man, with laser-like focus.",
        "The journey of a thousand miles begins with one step.",
        "If you don\u{2019}t like something, change it. If you can\u{2019}t change it, change your attitude.",
        "Defeat is not the worst of failures. Not to have tried is the true failure.",
        "Any change, even a change for the better, is always accompanied by drawbacks and discomforts.",
        "Failure is the condiment that gives success its flavor.",
        "The best way to predict the future is to create it.",
        "Our greatest glory is not in never falling, but in rising every time we fall.",
        "Start where you are. Use what you have. Do what you can.",
        "Dream big and dare to fail.",
        "We may encounter many defeats but we must not be defeated.",
        "Any problem is a chance for you to do your best."
    ]
}
